# fCC.ES6.handle-a-rejected-promise-with-catch
This is the code I used to complete the freeCodeCamp "handle a rejected promise with catch" challenge
